on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
      
    - name: Create output directory
      run: mkdir out
    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://orgb348fd10.crm.dynamics.com'
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
        solution-name: Test_Demo
        solution-output-file: 'aSolution.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/aSolution.zip'
        solution-folder: 'out/solutions/solution1'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: 'https://orgb348fd10.crm.dynamics.com'
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'out/solutions/solution1'
        solution-target-folder: 'src/solutions/solution1'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
